"""Per-node authentication tokens (CRKY-5, CRKY-69, CRKY-170).

Replaces the shared CK_AUTH_TOKEN with unique, revocable tokens tied
to an org. Each token is generated by an org admin and given to a
node operator. When a node registers with this token, it's associated
with the issuing org.

Tokens are stored in the dedicated ck.node_tokens Postgres table so
that generate / validate / revoke are atomic at the database level.
Previously this module stored every token inside one JSON blob in
ck.settings and did a non-atomic load -> mutate -> save on every call,
which meant a revocation could be silently overwritten by a concurrent
validate(). When Postgres is unavailable, the module falls back to the
JSON storage backend (non-atomic, dev/test only).
"""

from __future__ import annotations

import logging
import secrets
import time
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class NodeToken:
    """A per-node authentication token."""

    token: str
    org_id: str
    label: str  # human-readable name like "Render-Box-A"
    created_by: str  # user_id of who generated it
    created_at: float = 0.0
    last_used_at: float = 0.0
    node_id: str | None = None  # set when a node registers with this token
    revoked: bool = False

    def _storage_dict(self) -> dict[str, Any]:
        """Dict for storage — only dataclass fields, no computed values."""
        return {
            "token": self.token,
            "org_id": self.org_id,
            "label": self.label,
            "created_by": self.created_by,
            "created_at": self.created_at,
            "last_used_at": self.last_used_at,
            "node_id": self.node_id,
            "revoked": self.revoked,
        }

    def to_dict(self) -> dict[str, Any]:
        """Full dict including computed token_preview — for API responses."""
        d = self._storage_dict()
        d["token_preview"] = self.token[:8] + "..."
        return d

    def to_safe_dict(self) -> dict[str, Any]:
        """Dict without the full token — for listing."""
        d = self.to_dict()
        del d["token"]
        return d


# Column order used by every SELECT so we can build NodeToken from a row tuple.
_COLUMNS = (
    "token",
    "org_id",
    "label",
    "created_by",
    "created_at",
    "last_used_at",
    "node_id",
    "revoked",
)
_SELECT_COLS = ", ".join(_COLUMNS)


def _row_to_token(row: tuple) -> NodeToken:
    return NodeToken(
        token=row[0],
        org_id=row[1],
        label=row[2],
        created_by=row[3],
        created_at=float(row[4] or 0),
        last_used_at=float(row[5] or 0),
        node_id=row[6],
        revoked=bool(row[7]),
    )


class NodeTokenStore:
    """Manages per-node authentication tokens."""

    def __init__(self):
        from .database import get_storage

        self._storage = get_storage()

    # -- JSON fallback helpers -------------------------------------------------

    def _load(self) -> dict[str, dict]:
        return self._storage.get_setting("node_tokens", {})

    def _save(self, tokens: dict[str, dict]) -> None:
        self._storage.set_setting("node_tokens", tokens)

    @staticmethod
    def _clean(data: dict) -> dict:
        """Strip non-dataclass fields from stored data."""
        return {k: v for k, v in data.items() if k in NodeToken.__dataclass_fields__}

    # -- Public API ------------------------------------------------------------

    def generate(self, org_id: str, label: str, created_by: str) -> NodeToken:
        """Generate a new node token for an org."""
        from .database import get_pg_conn

        token = secrets.token_urlsafe(32)
        record = NodeToken(
            token=token,
            org_id=org_id,
            label=label,
            created_by=created_by,
            created_at=time.time(),
        )

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(
                    """INSERT INTO ck.node_tokens
                       (token, org_id, label, created_by, created_at,
                        last_used_at, node_id, revoked)
                       VALUES (%s, %s, %s, %s, %s, 0, NULL, FALSE)""",
                    (token, org_id, label, created_by, record.created_at),
                )
                cur.close()
                return record

        tokens = self._load()
        tokens[token] = record._storage_dict()
        self._save(tokens)
        return record

    def validate(self, token: str) -> NodeToken | None:
        """Validate a token. Returns the token record or None.

        Uses an atomic UPDATE ... WHERE revoked = FALSE RETURNING so a
        concurrent revoke() cannot be overwritten: if the row was
        revoked between fetch and update, no row is updated and the
        caller sees the token as invalid.
        """
        from .database import get_pg_conn

        if not token:
            return None

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(
                    f"""UPDATE ck.node_tokens
                        SET last_used_at = %s
                        WHERE token = %s AND revoked = FALSE
                        RETURNING {_SELECT_COLS}""",
                    (time.time(), token),
                )
                row = cur.fetchone()
                cur.close()
                return _row_to_token(row) if row else None

        tokens = self._load()
        data = tokens.get(token)
        if not data or data.get("revoked"):
            return None
        data["last_used_at"] = time.time()
        self._save(tokens)
        return NodeToken(**self._clean(data))

    def mark_used_by_node(self, token: str, node_id: str) -> None:
        """Associate a token with a specific node after registration."""
        from .database import get_pg_conn

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(
                    """UPDATE ck.node_tokens
                       SET node_id = %s, last_used_at = %s
                       WHERE token = %s""",
                    (node_id, time.time(), token),
                )
                cur.close()
                return

        tokens = self._load()
        if token in tokens:
            tokens[token]["node_id"] = node_id
            tokens[token]["last_used_at"] = time.time()
            self._save(tokens)

    def list_for_org(self, org_id: str) -> list[NodeToken]:
        """List all tokens for an org."""
        from .database import get_pg_conn

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(
                    f"SELECT {_SELECT_COLS} FROM ck.node_tokens WHERE org_id = %s",
                    (org_id,),
                )
                rows = cur.fetchall()
                cur.close()
                return [_row_to_token(r) for r in rows]

        tokens = self._load()
        return [NodeToken(**self._clean(v)) for v in tokens.values() if v.get("org_id") == org_id]

    def list_all(self) -> list[NodeToken]:
        """List all tokens (platform admin)."""
        from .database import get_pg_conn

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(f"SELECT {_SELECT_COLS} FROM ck.node_tokens")
                rows = cur.fetchall()
                cur.close()
                return [_row_to_token(r) for r in rows]

        tokens = self._load()
        return [NodeToken(**self._clean(v)) for v in tokens.values()]

    def revoke(self, token: str) -> bool:
        """Revoke a token. Returns True if found."""
        from .database import get_pg_conn

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute(
                    "UPDATE ck.node_tokens SET revoked = TRUE WHERE token = %s",
                    (token,),
                )
                found = cur.rowcount > 0
                cur.close()
                return found

        tokens = self._load()
        if token not in tokens:
            return False
        tokens[token]["revoked"] = True
        self._save(tokens)
        return True

    def delete(self, token: str) -> bool:
        """Delete a token entirely."""
        from .database import get_pg_conn

        with get_pg_conn() as conn:
            if conn is not None:
                cur = conn.cursor()
                cur.execute("DELETE FROM ck.node_tokens WHERE token = %s", (token,))
                found = cur.rowcount > 0
                cur.close()
                return found

        tokens = self._load()
        if token not in tokens:
            return False
        del tokens[token]
        self._save(tokens)
        return True


# Singleton
_store: NodeTokenStore | None = None


def get_node_token_store() -> NodeTokenStore:
    global _store
    if _store is None:
        _store = NodeTokenStore()
    return _store
